# Generated by nivra init zsh. No startup files are modified automatically.
# Re-sourcing updates the binary path without installing duplicate hooks.
typeset -g _NIVRA_BIN=__NIVRA_BINARY__
typeset -g _NIVRA_SESSION=__NIVRA_SESSION__
autoload -Uz add-zsh-hook
_nivra_preexec() {
  local previous_status=$?
  local text="$1"
  # Explicit run owns its own event. Management commands are not captured.
  if [[ "$text" == nivra || "$text" == nivra\ * || "$text" == "$_NIVRA_BIN"* ]]; then
    return $previous_status
  fi
  _NIVRA_EVENT=$(print -rn -- "$text" | "$_NIVRA_BIN" hook start --session "$_NIVRA_SESSION" 2>/dev/null) || _NIVRA_EVENT=''
  return $previous_status
}
_nivra_precmd() {
  local command_status=$?
  if [[ -n "${_NIVRA_EVENT:-}" ]]; then
    "$_NIVRA_BIN" hook end --id "$_NIVRA_EVENT" --exit-code "$command_status" 2>/dev/null >/dev/null || true
    _NIVRA_EVENT=''
  fi
  return $command_status
}
add-zsh-hook -d preexec _nivra_preexec 2>/dev/null
add-zsh-hook -d precmd _nivra_precmd 2>/dev/null
add-zsh-hook preexec _nivra_preexec
add-zsh-hook precmd _nivra_precmd
